version: '2'
services:
  web:
    image: nginx:1.15.1
    container_name: app_web
    ports:
      - "8080:80"
    volumes:
      - ./../:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mysql
    networks:
      - appnet
  php:
    build: ./php
    image: lukeparkinson/php
    container_name: app_php
    volumes:
      - ./../:/code
    links:
      - mysql
      - redis
      - mailhog
    networks:
      - appnet
  mysql:
    image: mysql:5.7.21
    container_name: app_mysql
    ports:
      - "3366:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: password
    networks:
      - appnet
  mailhog:
    image: mailhog/mailhog
    container_name: app_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - appnet
  redis:
    image: redis:3.2.11
    container_name: app_redis
    ports:
      - "6379:6379"
    networks:
      - appnet
  cloud9:
    image: kdelfour/cloud9-docker
    container_name: app_ide
    volumes:
      - ./../:/workspace/
    ports:
      - "8081:80"
    networks:
      - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: application
      PMA_PASSWORD: password
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
