web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./../:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
        - db

php:
    build: ./php
    volumes:
        - ./../:/code
    links:
        - db
        - mailhog

db:
    image: mysql
    ports:
        - "3366:3306"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: application
        MYSQL_USER: application
        MYSQL_PASSWORD: password

mailhog:
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"
