web:
    image: nginx:1.13.9
    ports:
        - "8080:80"
    volumes:
        - ./../:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
        - db

php:
    build: ./php
    volumes:
        - ./../:/code
    links:
        - db
        - redis
        - mailhog

db:
    image: mysql:5.7.21
    ports:
        - "3366:3306"
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: application
        MYSQL_USER: application
        MYSQL_PASSWORD: password

mailhog:
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"

redis:
    image: redis:3.2.11
    ports:
        - "6379:6379"