version: '2'
services:
  web:
    image: nginx:1.13.9
    ports:
      - "8080:80"
    volumes:
      - ./../:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
      - mysql
    networks:
      - appnet
  php:
    build: ./php
    volumes:
      - ./../:/code
    links:
      - mysql
      - redis
      - mailhog
    networks:
      - appnet
  mysql:
    image: mysql:5.7.21
    ports:
      - "3366:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: password
    networks:
      - appnet
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - appnet
  redis:
    image: redis:3.2.11
    ports:
      - "6379:6379"
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
